### ISSUE TITLE
doc for different arch

### ISSUE THREAD

**Issue by solsticedhiver** [anatol/pacoloco#11]
The tip found on [aur.archlinux.org](aur.archlinux.org) about the use of different **arch** should definitvly be in the README.md or in some sort of doc.

```
If you need to proxy pacman databases for different arches then you need to have multiple different repos:

repos:
  archlinux_x86_64:
    urls:
      - http://mirror.lty.me/archlinux
      - http://mirrors.kernel.org/archlinux
 archlinux_arm:
    urls:
      - http://foo.bar/archlinux/arm
      - http://bar.foo/another_arch_arm_repo
Then modify pacman.conf to point to the repo with the required architecture http://myserver:9129/repo/archlinux_$arch
```
