### ISSUE TITLE
Cache breaks if multiple repos have the same package and package version

### ISSUE THREAD

**Issue by obj-obj** [anatol/pacoloco#114]
An example of this is https://somegit.dev/ALHP/ALHP.GO, which has multiple repos for different x86_64 feature levels, with the exact same packages in each repo. 

As you can see below, the cache does not differentiate between different repositories, so it would place the `pacman-contrib` package from both the `x86-64-v4` and `x86-64-v3` repositories in the same place, causing it to be invalid for one of the two repos:

![Screenshot_20240727_011129](https://github.com/user-attachments/assets/76259558-712a-4d91-bf02-7aced42cad74)
![Screenshot_20240727_011435](https://github.com/user-attachments/assets/3e7651de-a9b1-41a9-94bd-4f02ec44f924)

**Comment by anatol** [comment]
Could you please post your pacoloco config file?

**Comment by obj-obj** [comment]
> Could you please post your pacoloco config file?

```yaml
# cache_dir: /var/cache/pacoloco
# port: 9129
download_timeout: 3600 ## downloads will timeout if not completed after 3600 sec, 0 to disable timeout
purge_files_after: 2592000 ## purge file after 30 days
# set_timestamp_to_logs: true ## uncomment to add timestamp, useful if pacoloco is being ran through docker

repos:
  archlinux:
    urls: ## add or change official mirror urls as desired, see https://archlinux.org/mirrors/status/
      - https://cloudflaremirrors.com/archlinux/
  alhpv3:
    mirrorlist: /etc/pacman.d/alhp-mirrorlist
  alhpv4:
    mirrorlist: /etc/pacman.d/alhp-mirrorlist
  chaotic:
    mirrorlist: /etc/pacman.d/chaotic-mirrorlist
## Local/3rd party repos can be added following the below example:
#  quarry:
#    http_proxy: http://bar.company.com:8989 ## Proxy could be enabled per-repo, shadowing the global `http_proxy` (see below)
#    url: http://pkgbuild.com/~anatolik/quarry/x86_64

# prefetch: ## optional section, add it if you want to enable prefetching
#  cron: 0 0 3 * * * * ## standard cron expression (https://en.wikipedia.org/wiki/Cron#CRON_expression) to define how frequently prefetch, see https://github.com/gorhill/cronexpr#implementation for documentation.
#  ttl_unaccessed_in_days: 30  ## defaults to 30, set it to a higher value than the number of consecutive days you don't update your systems
    ## It deletes and stops prefetching packages (and db links) when not downloaded after "ttl_unaccessed_in_days" days that it has been updated.
#  ttl_unupdated_in_days: 300 ## defaults to 300, it deletes and stops prefetching packages which haven't been either updated upstream or requested for "ttl_unupdated_in_days".
# http_proxy: http://proxy.company.com:8888 ## Enable this if you have pacoloco running behind a proxy
# user_agent: Pacoloco/1.2
```
Previously `alhpv3` and `alhpv4` were under one entry called `alhp`, but I ran into this issue.
