### ISSUE TITLE
Mirroring Debian repos

### ISSUE THREAD

**Issue by dezeroku** [anatol/pacoloco#121]
Hi,
thanks for the great work again!

Some time ago I've set up few Debian servers and I'd like to set up a caching update server for these, similar as I already have for my Arch machines.
Now, I'm aware that there are already multiple solutions that can do that for `apt` repos, but considering that I've already have `pacoloco` deployed and I'm happy with it I wondered if it could be used for that purpose.

Setting up a single repo as such:
```
repos:
  debian:
    url: https://mirrors.edge.kernel.org/debian
```
with the following node config:
```
deb https://<pacoloco-url>/repo/debian bookworm main non-free-firmware
deb https://<pacoloco-url>/repo/debian bookworm-updates main non-free-firmware
```
doesn't work nicely, as `bookworm` and `bookworm-updates` seem to fight over ownership of some common repo files.

That's ok, I suppose it's a similar case as with multiple architectures, so I've split these repos:
```
repos:
  debian:
    url: https://mirrors.edge.kernel.org/debian
  debian-updates:
    url: https://mirrors.edge.kernel.org/debian
  debian-security:
    url: https://security.debian.org/debian-security
```
and aligned the node config to the new setup:
```
deb https://<pacoloco-url>/repo/debian bookworm main non-free-firmware
deb https://<pacoloco-url>/repo/debian-updates bookworm-updates main non-free-firmware
deb https://<pacoloco-url>/repo/debian-security bookworm-security main non-free-firmware
```
and it seems to work fine and cache the packages correctly.

I guess I want to ask if it's a good idea to keep it that way.
Is there any "Arch Linux specific" stuff implemented that would not allow `pacoloco` to be used as a general caching proxy?

Of course I'm aware that supporting such scenario is not really in scope of this project, so any issues related to mirroring Debian I might run into I am on my own.
