### ISSUE TITLE
connection refused - dockerized

### ISSUE THREAD

**Issue by travnick** [anatol/pacoloco#123]
I'm struggling to setup dockerized pacoloco.

```
root ~ # LANG=C pacman -Syu
:: Synchronizing package databases...
 core.db failed to download
error: failed retrieving file 'core.db' from my-host.local:9129 : Failed to connect to my-host.local port 9129 after 106 ms: Could not connect to server
error: failed to synchronize all databases (failed to retrieve some files)
```
also refused inside container 
```
/pacoloco # wget localhost:9129
Connecting to localhost:9129 ([::1]:9129)
wget: can't connect to remote host: Connection refused

/pacoloco # netstat -tulp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 localhost:34271         0.0.0.0:*               LISTEN      -
tcp        0      0 localhost:9129          0.0.0.0:*               LISTEN      1/pacoloco
udp        0      0 localhost:59590         0.0.0.0:*                           -/
```

docker compose file on `my-host.local` (OMV instance):
```
services:
  reflector:
    container_name: reflector
    image: ghcr.io/dezeroku/arch_linux_reflector_docker:latest
    command: --latest 20 --sort rate --score 10 --save /home/reflector/mirrorlist
    volumes:
      - reflector:/home/reflector

  pacoloco:
    container_name: pacoloco
    image: ghcr.io/anatol/pacoloco
    command: /pacoloco/pacoloco --config /etc/pacoloco/pacoloco.yaml
    ports:
      - "9129:9129"
    volumes:
      - cache:/var/cache/pacoloco
      - config:/etc/pacoloco
      - reflector:/home/reflector

    restart: unless-stopped

volumes:
  cache:
  config:
  reflector:
```

Also, I'm facing issues with initial setup.
Before manual creation of `pkgs/archlinux-reflector` in cache volume:
```
pacoloco.go:98: Reading config file from /etc/pacoloco/pacoloco.yaml
prefetch.go:45: The prefetching routine will be run on 2025-01-06 07:00:00.000397473 +0000 UTC m=+50575.237081616
pacoloco.go:117: Gathering size failed for  archlinux-reflector
pacoloco.go:141: Starting server at address 127.0.0.1:9129
purge.go:67: lstat /var/cache/pacoloco/pkgs/archlinux-reflector: no such file or directory
```
after manual create:
```
pacoloco.go:98: Reading config file from /etc/pacoloco/pacoloco.yaml
prefetch.go:45: The prefetching routine will be run on 2025-01-06 07:00:00.000254123 +0000 UTC m=+50545.119812892
pacoloco.go:141: Starting server at address 127.0.0.1:9129
```
(the database file `sqlite-pkg-cache.db` was automatically created)
