### ISSUE TITLE
docker-compose build fails.

### ISSUE THREAD

**Issue by gary094** [anatol/pacoloco#33]
Hi! I created a docker-compose file to easily bring up the proxy however I am facing the following error:

This is my docker-compose.yml:

```
---
version: "3.3"
services:
  pacoloco:
    container_name: pacoloco
    build: https://github.com/anatol/pacoloco.git
    ports:
      - "9129:9129"
    volumes:
      - /mnt/pacoloco/cache:/var/cache/pacoloco/pkgs
      - /mnt/pacoloco/config/pacoloco.yaml:/etc/pacoloco.yaml
    networks:
      - pacoloco

networks:
  pacoloco:
    external: true
```

to start this I use:

`sudo docker-compose -f docker-compose-pacoloco.yml up`

and as a result I get:

```
Starting pacoloco ... done
Attaching to pacoloco
pacoloco    | pacoloco.go:104: Reading config file from /etc/pacoloco.yaml
pacoloco    | prefetch.go:34: The prefetching routine will be run on 2021-11-11 03:00:00.000052408 +0000 UTC m=+28762.631952104
pacoloco    | prefetch.go:67: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub
pacoloco exited with code 1
```

Unfortunately I have no expertise with Go so I would appreciate if you could give me some hint to fix this issue.

Thanks.
