### ISSUE TITLE
cron not working with commas

### ISSUE THREAD

**Issue by Loader009** [anatol/pacoloco#36]
I defined a few specific hours for downloading automatically.
This doesn't seem to work, as my journal told me `journalctl -t pacoloco`.

In pacoloco.yml:
```yaml
prefetch:
  cron: 0 30 1,9,16 * * * *
  ttl_unaccessed_in_days: 30
  ttl_unupdated_in_days: 300
```

This should mean: on 30 minutes at 1 am, 9 am and 4 pm, everyday.
Have I done something wrong or is the cron implementation wrong?
