### ISSUE TITLE
Simplify default pacoloco.yaml config

### ISSUE THREAD

**Issue by ericlay** [anatol/pacoloco#81]
I found it a little confusing to have the optional repositories included in the installed config file [`pacoloco.yaml`](https://github.com/anatol/pacoloco/blob/master/pacoloco.yaml.sample)
```
 quarry:
    url: http://pkgbuild.com/~anatolik/quarry/x86_64
 sublime:
    url: https://download.sublimetext.com/arch/stable/x86_64
```

It is not noted in the [configuration section](https://github.com/anatol/pacoloco#configure) that these are purely optional.  And possibly lead those who are unaware to have unused extra repositories configured. 

Arch wiki has a [sample config](https://wiki.archlinux.org/title/Pacman/Tips_and_tricks#Pacoloco_proxy_cache_server) that is a lot more bare bones.
```
port: 9129
repos:
  mycopy:
    urls:
      - http://mirror.lty.me/archlinux
      - http://mirrors.kernel.org/archlinux
```

IMO moving the sample config as is to `/usr/share` and documenting both the optional repositories as well the need to edit/move/recreate the file in `/etc` would be a more appropriate method.

At minimum, please signify that these are purely optional repositories and are not needed to function somewhere in the  [configuration section](https://github.com/anatol/pacoloco#configure)?
