### ISSUE TITLE
pacoloco.yaml urls: syntax for EndeavourOS

### ISSUE THREAD

**Issue by fhteagle** [anatol/pacoloco#91]
Tried to follow the example in #37 for EndeavourOS repos , but I am getting a spurious /os/ path segment added to the download URLs, causing download failure.

my pacoloco.yaml 
```
...
repos:
  archlinux_x86_64:
    urls:
      - http://mirrors.gigenet.com/archlinux
...
  endeavouros:
    urls:
      - https://mirrors.gigenet.com/endeavouros/repo
...
```

But in docker container logs:
```
...
2023-09-07T16:34:07.799325913Z downloader.go:102: downloading https://mirrors.gigenet.com/endeavouros/repo/endeavouros/os/x86_64/endeavouros-keyring-20230523-1-any.pkg.tar.zst
...
```     

Correct URL for that repo would be:
```
https://mirrors.gigenet.com/endeavouros/repo/endeavouros/x86_64/endeavouros-keyring-20230523-1-any.pkg.tar.zst
```

I also tried massaging the pacoloco.yaml with various $repo and $arch token combinations, but in every case I get an extra /os/ path segment .... 

What do I need to change the endeavouros URL lines to?

Thanks
